#
# @package No Duplicate phpBB SEO
# @version $$
# @copyright (c) 2014 www.phpbb-seo.com
# @license http://opensource.org/licenses/gpl-2.0.php GNU General Public License v2
#
# You must indent with 4 spaces instead of 1 tab
#
services: 
    phpbbseo.nodupe.listener:
        class: phpbbseo\nodupe\event\listener
        arguments:
            - '@config'
            - '@auth'
            - '@user'
            - %core.root_path%
            - %core.php_ext%
            - '@?phpbbseo.usu.core'
        tags:
            - { name: event.listener }
